INSERT INTO `city` VALUES (1, 1, 'تبريز');
INSERT INTO `city` VALUES (2, 1, 'كندوان');
INSERT INTO `city` VALUES (3, 1, 'بندر شرفخانه');
INSERT INTO `city` VALUES (4, 1, 'مراغه');
INSERT INTO `city` VALUES (5, 1, 'ميانه');
INSERT INTO `city` VALUES (6, 1, 'شبستر');
INSERT INTO `city` VALUES (7, 1, 'مرند');
INSERT INTO `city` VALUES (8, 1, 'جلفا');
INSERT INTO `city` VALUES (9, 1, 'سراب');
INSERT INTO `city` VALUES (10, 1, 'هاديشهر');
INSERT INTO `city` VALUES (11, 1, 'بناب');
INSERT INTO `city` VALUES (12, 1, 'كليبر');
INSERT INTO `city` VALUES (13, 1, 'تسوج');
INSERT INTO `city` VALUES (14, 1, 'اهر');
INSERT INTO `city` VALUES (15, 1, 'هريس');
INSERT INTO `city` VALUES (16, 1, 'عجبشير');
INSERT INTO `city` VALUES (17, 1, 'هشترود');
INSERT INTO `city` VALUES (18, 1, 'ملكان');
INSERT INTO `city` VALUES (19, 1, 'بستان آباد');
INSERT INTO `city` VALUES (20, 1, 'ورزقان');
INSERT INTO `city` VALUES (21, 1, 'اسكو');
INSERT INTO `city` VALUES (22, 1, 'آذر شهر');
INSERT INTO `city` VALUES (23, 1, 'قره آغاج');
INSERT INTO `city` VALUES (24, 1, 'ممقان');
INSERT INTO `city` VALUES (25, 1, 'صوفیان');
INSERT INTO `city` VALUES (26, 1, 'ایلخچی');
INSERT INTO `city` VALUES (27, 1, 'خسروشهر');
INSERT INTO `city` VALUES (28, 1, 'باسمنج');
INSERT INTO `city` VALUES (29, 1, 'سهند');
INSERT INTO `city` VALUES (30, 2, 'اروميه');
INSERT INTO `city` VALUES (31, 2, 'نقده');
INSERT INTO `city` VALUES (32, 2, 'ماكو');
INSERT INTO `city` VALUES (33, 2, 'تكاب');
INSERT INTO `city` VALUES (34, 2, 'خوي');
INSERT INTO `city` VALUES (35, 2, 'مهاباد');
INSERT INTO `city` VALUES (36, 2, 'سر دشت');
INSERT INTO `city` VALUES (37, 2, 'چالدران');
INSERT INTO `city` VALUES (38, 2, 'بوكان');
INSERT INTO `city` VALUES (39, 2, 'مياندوآب');
INSERT INTO `city` VALUES (40, 2, 'سلماس');
INSERT INTO `city` VALUES (41, 2, 'شاهين دژ');
INSERT INTO `city` VALUES (42, 2, 'پيرانشهر');
INSERT INTO `city` VALUES (43, 2, 'سيه چشمه');
INSERT INTO `city` VALUES (44, 2, 'اشنويه');
INSERT INTO `city` VALUES (45, 2, 'چایپاره');
INSERT INTO `city` VALUES (46, 2, 'پلدشت');
INSERT INTO `city` VALUES (47, 2, 'شوط');
INSERT INTO `city` VALUES (48, 3, 'اردبيل');
INSERT INTO `city` VALUES (49, 3, 'سرعين');
INSERT INTO `city` VALUES (50, 3, 'بيله سوار');
INSERT INTO `city` VALUES (51, 3, 'پارس آباد');
INSERT INTO `city` VALUES (52, 3, 'خلخال');
INSERT INTO `city` VALUES (53, 3, 'مشگين شهر');
INSERT INTO `city` VALUES (54, 3, 'مغان');
INSERT INTO `city` VALUES (55, 3, 'نمين');
INSERT INTO `city` VALUES (56, 3, 'نير');
INSERT INTO `city` VALUES (57, 3, 'كوثر');
INSERT INTO `city` VALUES (58, 3, 'كيوي');
INSERT INTO `city` VALUES (59, 3, 'گرمي');
INSERT INTO `city` VALUES (60, 4, 'اصفهان');
INSERT INTO `city` VALUES (61, 4, 'فريدن');
INSERT INTO `city` VALUES (62, 4, 'فريدون شهر');
INSERT INTO `city` VALUES (63, 4, 'فلاورجان');
INSERT INTO `city` VALUES (64, 4, 'گلپايگان');
INSERT INTO `city` VALUES (65, 4, 'دهاقان');
INSERT INTO `city` VALUES (66, 4, 'نطنز');
INSERT INTO `city` VALUES (67, 4, 'نايين');
INSERT INTO `city` VALUES (68, 4, 'تيران');
INSERT INTO `city` VALUES (69, 4, 'كاشان');
INSERT INTO `city` VALUES (70, 4, 'فولاد شهر');
INSERT INTO `city` VALUES (71, 4, 'اردستان');
INSERT INTO `city` VALUES (72, 4, 'سميرم');
INSERT INTO `city` VALUES (73, 4, 'درچه');
INSERT INTO `city` VALUES (74, 4, 'کوهپایه');
INSERT INTO `city` VALUES (75, 4, 'مباركه');
INSERT INTO `city` VALUES (76, 4, 'شهرضا');
INSERT INTO `city` VALUES (77, 4, 'خميني شهر');
INSERT INTO `city` VALUES (78, 4, 'شاهين شهر');
INSERT INTO `city` VALUES (79, 4, 'نجف آباد');
INSERT INTO `city` VALUES (80, 4, 'دولت آباد');
INSERT INTO `city` VALUES (81, 4, 'زرين شهر');
INSERT INTO `city` VALUES (82, 4, 'آران و بيدگل');
INSERT INTO `city` VALUES (83, 4, 'باغ بهادران');
INSERT INTO `city` VALUES (84, 4, 'خوانسار');
INSERT INTO `city` VALUES (85, 4, 'مهردشت');
INSERT INTO `city` VALUES (86, 4, 'علويجه');
INSERT INTO `city` VALUES (87, 4, 'عسگران');
INSERT INTO `city` VALUES (88, 4, 'نهضت آباد');
INSERT INTO `city` VALUES (89, 4, 'حاجي آباد');
INSERT INTO `city` VALUES (90, 4, 'تودشک');
INSERT INTO `city` VALUES (91, 4, 'ورزنه');
INSERT INTO `city` VALUES (92, 6, 'ايلام');
INSERT INTO `city` VALUES (93, 6, 'مهران');
INSERT INTO `city` VALUES (94, 6, 'دهلران');
INSERT INTO `city` VALUES (95, 6, 'آبدانان');
INSERT INTO `city` VALUES (96, 6, 'شيروان چرداول');
INSERT INTO `city` VALUES (97, 6, 'دره شهر');
INSERT INTO `city` VALUES (98, 6, 'ايوان');
INSERT INTO `city` VALUES (99, 6, 'سرابله');
INSERT INTO `city` VALUES (100, 7, 'بوشهر');
INSERT INTO `city` VALUES (101, 7, 'تنگستان');
INSERT INTO `city` VALUES (102, 7, 'دشتستان');
INSERT INTO `city` VALUES (103, 7, 'دير');
INSERT INTO `city` VALUES (104, 7, 'ديلم');
INSERT INTO `city` VALUES (105, 7, 'كنگان');
INSERT INTO `city` VALUES (106, 7, 'گناوه');
INSERT INTO `city` VALUES (107, 7, 'ريشهر');
INSERT INTO `city` VALUES (108, 7, 'دشتي');
INSERT INTO `city` VALUES (109, 7, 'خورموج');
INSERT INTO `city` VALUES (110, 7, 'اهرم');
INSERT INTO `city` VALUES (111, 7, 'برازجان');
INSERT INTO `city` VALUES (112, 7, 'خارك');
INSERT INTO `city` VALUES (113, 7, 'جم');
INSERT INTO `city` VALUES (114, 7, 'کاکی');
INSERT INTO `city` VALUES (115, 7, 'عسلویه');
INSERT INTO `city` VALUES (116, 7, 'بردخون');
INSERT INTO `city` VALUES (117, 8, 'تهران');
INSERT INTO `city` VALUES (118, 8, 'ورامين');
INSERT INTO `city` VALUES (119, 8, 'فيروزكوه');
INSERT INTO `city` VALUES (120, 8, 'ري');
INSERT INTO `city` VALUES (121, 8, 'دماوند');
INSERT INTO `city` VALUES (122, 8, 'اسلامشهر');
INSERT INTO `city` VALUES (123, 8, 'رودهن');
INSERT INTO `city` VALUES (124, 8, 'لواسان');
INSERT INTO `city` VALUES (125, 8, 'بومهن');
INSERT INTO `city` VALUES (126, 8, 'تجريش');
INSERT INTO `city` VALUES (127, 8, 'فشم');
INSERT INTO `city` VALUES (128, 8, 'كهريزك');
INSERT INTO `city` VALUES (129, 8, 'پاكدشت');
INSERT INTO `city` VALUES (130, 8, 'چهاردانگه');
INSERT INTO `city` VALUES (131, 8, 'شريف آباد');
INSERT INTO `city` VALUES (132, 8, 'قرچك');
INSERT INTO `city` VALUES (133, 8, 'باقرشهر');
INSERT INTO `city` VALUES (134, 8, 'شهريار');
INSERT INTO `city` VALUES (135, 8, 'رباط كريم');
INSERT INTO `city` VALUES (136, 8, 'قدس');
INSERT INTO `city` VALUES (137, 8, 'ملارد');
INSERT INTO `city` VALUES (138, 9, 'شهركرد');
INSERT INTO `city` VALUES (139, 9, 'فارسان');
INSERT INTO `city` VALUES (140, 9, 'بروجن');
INSERT INTO `city` VALUES (141, 9, 'چلگرد');
INSERT INTO `city` VALUES (142, 9, 'اردل');
INSERT INTO `city` VALUES (143, 9, 'لردگان');
INSERT INTO `city` VALUES (144, 9, 'سامان');
INSERT INTO `city` VALUES (145, 10, 'قائن');
INSERT INTO `city` VALUES (146, 10, 'فردوس');
INSERT INTO `city` VALUES (147, 10, 'بيرجند');
INSERT INTO `city` VALUES (148, 10, 'نهبندان');
INSERT INTO `city` VALUES (149, 10, 'سربيشه');
INSERT INTO `city` VALUES (150, 10, 'طبس مسینا');
INSERT INTO `city` VALUES (151, 10, 'قهستان');
INSERT INTO `city` VALUES (152, 10, 'درمیان');
INSERT INTO `city` VALUES (153, 11, 'مشهد');
INSERT INTO `city` VALUES (154, 11, 'نيشابور');
INSERT INTO `city` VALUES (155, 11, 'سبزوار');
INSERT INTO `city` VALUES (156, 11, 'كاشمر');
INSERT INTO `city` VALUES (157, 11, 'گناباد');
INSERT INTO `city` VALUES (158, 11, 'طبس');
INSERT INTO `city` VALUES (159, 11, 'تربت حيدريه');
INSERT INTO `city` VALUES (160, 11, 'خواف');
INSERT INTO `city` VALUES (161, 11, 'تربت جام');
INSERT INTO `city` VALUES (162, 11, 'تايباد');
INSERT INTO `city` VALUES (163, 11, 'قوچان');
INSERT INTO `city` VALUES (164, 11, 'سرخس');
INSERT INTO `city` VALUES (165, 11, 'بردسكن');
INSERT INTO `city` VALUES (166, 11, 'فريمان');
INSERT INTO `city` VALUES (167, 11, 'چناران');
INSERT INTO `city` VALUES (168, 11, 'درگز');
INSERT INTO `city` VALUES (169, 11, 'كلات');
INSERT INTO `city` VALUES (170, 11, 'طرقبه');
INSERT INTO `city` VALUES (171, 11, 'سر ولایت');
INSERT INTO `city` VALUES (172, 12, 'بجنورد');
INSERT INTO `city` VALUES (173, 12, 'اسفراين');
INSERT INTO `city` VALUES (174, 12, 'جاجرم');
INSERT INTO `city` VALUES (175, 12, 'شيروان');
INSERT INTO `city` VALUES (176, 12, 'آشخانه');
INSERT INTO `city` VALUES (177, 12, 'گرمه');
INSERT INTO `city` VALUES (178, 12, 'ساروج');
INSERT INTO `city` VALUES (179, 13, 'اهواز');
INSERT INTO `city` VALUES (180, 13, 'ايرانشهر');
INSERT INTO `city` VALUES (181, 13, 'شوش');
INSERT INTO `city` VALUES (182, 13, 'آبادان');
INSERT INTO `city` VALUES (183, 13, 'خرمشهر');
INSERT INTO `city` VALUES (184, 13, 'مسجد سليمان');
INSERT INTO `city` VALUES (185, 13, 'ايذه');
INSERT INTO `city` VALUES (186, 13, 'شوشتر');
INSERT INTO `city` VALUES (187, 13, 'انديمشك');
INSERT INTO `city` VALUES (188, 13, 'سوسنگرد');
INSERT INTO `city` VALUES (189, 13, 'هويزه');
INSERT INTO `city` VALUES (190, 13, 'دزفول');
INSERT INTO `city` VALUES (191, 13, 'شادگان');
INSERT INTO `city` VALUES (192, 13, 'بندر ماهشهر');
INSERT INTO `city` VALUES (193, 13, 'بندر امام خميني');
INSERT INTO `city` VALUES (194, 13, 'اميديه');
INSERT INTO `city` VALUES (195, 13, 'بهبهان');
INSERT INTO `city` VALUES (196, 13, 'رامهرمز');
INSERT INTO `city` VALUES (197, 13, 'باغ ملك');
INSERT INTO `city` VALUES (198, 13, 'هنديجان');
INSERT INTO `city` VALUES (199, 13, 'لالي');
INSERT INTO `city` VALUES (200, 13, 'رامشیر');
INSERT INTO `city` VALUES (201, 13, 'حمیدیه');
INSERT INTO `city` VALUES (202, 13, 'دغاغله');
INSERT INTO `city` VALUES (203, 13, 'ملاثانی');
INSERT INTO `city` VALUES (204, 13, 'شادگان');
INSERT INTO `city` VALUES (205, 13, 'ویسی');
INSERT INTO `city` VALUES (206, 14, 'زنجان');
INSERT INTO `city` VALUES (207, 14, 'ابهر');
INSERT INTO `city` VALUES (208, 14, 'خدابنده');
INSERT INTO `city` VALUES (209, 14, 'كارم');
INSERT INTO `city` VALUES (210, 14, 'ماهنشان');
INSERT INTO `city` VALUES (211, 14, 'خرمدره');
INSERT INTO `city` VALUES (212, 14, 'ايجرود');
INSERT INTO `city` VALUES (213, 14, 'زرين آباد');
INSERT INTO `city` VALUES (214, 14, 'آب بر');
INSERT INTO `city` VALUES (215, 14, 'قيدار');
INSERT INTO `city` VALUES (216, 15, 'سمنان');
INSERT INTO `city` VALUES (217, 15, 'شاهرود');
INSERT INTO `city` VALUES (218, 15, 'گرمسار');
INSERT INTO `city` VALUES (219, 15, 'ايوانكي');
INSERT INTO `city` VALUES (220, 15, 'دامغان');
INSERT INTO `city` VALUES (221, 15, 'بسطام');
INSERT INTO `city` VALUES (222, 16, 'زاهدان');
INSERT INTO `city` VALUES (223, 16, 'چابهار');
INSERT INTO `city` VALUES (224, 16, 'خاش');
INSERT INTO `city` VALUES (225, 16, 'سراوان');
INSERT INTO `city` VALUES (226, 16, 'زابل');
INSERT INTO `city` VALUES (227, 16, 'سرباز');
INSERT INTO `city` VALUES (228, 16, 'نيكشهر');
INSERT INTO `city` VALUES (229, 16, 'ايرانشهر');
INSERT INTO `city` VALUES (230, 16, 'راسك');
INSERT INTO `city` VALUES (231, 16, 'ميرجاوه');
INSERT INTO `city` VALUES (232, 17, 'شيراز');
INSERT INTO `city` VALUES (233, 17, 'اقليد');
INSERT INTO `city` VALUES (234, 17, 'داراب');
INSERT INTO `city` VALUES (235, 17, 'فسا');
INSERT INTO `city` VALUES (236, 17, 'مرودشت');
INSERT INTO `city` VALUES (237, 17, 'خرم بيد');
INSERT INTO `city` VALUES (238, 17, 'آباده');
INSERT INTO `city` VALUES (239, 17, 'كازرون');
INSERT INTO `city` VALUES (240, 17, 'ممسني');
INSERT INTO `city` VALUES (241, 17, 'سپيدان');
INSERT INTO `city` VALUES (242, 17, 'لار');
INSERT INTO `city` VALUES (243, 17, 'فيروز آباد');
INSERT INTO `city` VALUES (244, 17, 'جهرم');
INSERT INTO `city` VALUES (245, 17, 'ني ريز');
INSERT INTO `city` VALUES (246, 17, 'استهبان');
INSERT INTO `city` VALUES (247, 17, 'لامرد');
INSERT INTO `city` VALUES (248, 17, 'مهر');
INSERT INTO `city` VALUES (249, 17, 'حاجي آباد');
INSERT INTO `city` VALUES (250, 17, 'نورآباد');
INSERT INTO `city` VALUES (251, 17, 'اردكان');
INSERT INTO `city` VALUES (252, 17, 'صفاشهر');
INSERT INTO `city` VALUES (253, 17, 'ارسنجان');
INSERT INTO `city` VALUES (254, 17, 'قيروكارزين');
INSERT INTO `city` VALUES (255, 17, 'سوريان');
INSERT INTO `city` VALUES (256, 17, 'فراشبند');
INSERT INTO `city` VALUES (257, 17, 'سروستان');
INSERT INTO `city` VALUES (258, 17, 'ارژن');
INSERT INTO `city` VALUES (259, 17, 'گويم');
INSERT INTO `city` VALUES (260, 17, 'داريون');
INSERT INTO `city` VALUES (261, 17, 'زرقان');
INSERT INTO `city` VALUES (262, 17, 'خان زنیان');
INSERT INTO `city` VALUES (263, 17, 'کوار');
INSERT INTO `city` VALUES (264, 17, 'ده بید');
INSERT INTO `city` VALUES (265, 17, 'باب انار/خفر');
INSERT INTO `city` VALUES (266, 17, 'بوانات');
INSERT INTO `city` VALUES (267, 17, 'خرامه');
INSERT INTO `city` VALUES (268, 17, 'خنج');
INSERT INTO `city` VALUES (269, 17, 'سیاخ دارنگون');
INSERT INTO `city` VALUES (270, 18, 'قزوين');
INSERT INTO `city` VALUES (271, 18, 'تاكستان');
INSERT INTO `city` VALUES (272, 18, 'آبيك');
INSERT INTO `city` VALUES (273, 18, 'بوئين زهرا');
INSERT INTO `city` VALUES (274, 19, 'قم');
INSERT INTO `city` VALUES (275, 5, 'طالقان');
INSERT INTO `city` VALUES (276, 5, 'نظرآباد');
INSERT INTO `city` VALUES (277, 5, 'اشتهارد');
INSERT INTO `city` VALUES (278, 5, 'هشتگرد');
INSERT INTO `city` VALUES (279, 5, 'كن');
INSERT INTO `city` VALUES (280, 5, 'آسارا');
INSERT INTO `city` VALUES (281, 5, 'شهرک گلستان');
INSERT INTO `city` VALUES (282, 5, 'اندیشه');
INSERT INTO `city` VALUES (283, 5, 'كرج');
INSERT INTO `city` VALUES (284, 5, 'نظر آباد');
INSERT INTO `city` VALUES (285, 5, 'گوهردشت');
INSERT INTO `city` VALUES (286, 5, 'ماهدشت');
INSERT INTO `city` VALUES (287, 5, 'مشکین دشت');
INSERT INTO `city` VALUES (288, 20, 'سنندج');
INSERT INTO `city` VALUES (289, 20, 'ديواندره');
INSERT INTO `city` VALUES (290, 20, 'بانه');
INSERT INTO `city` VALUES (291, 20, 'بيجار');
INSERT INTO `city` VALUES (292, 20, 'سقز');
INSERT INTO `city` VALUES (293, 20, 'كامياران');
INSERT INTO `city` VALUES (294, 20, 'قروه');
INSERT INTO `city` VALUES (295, 20, 'مريوان');
INSERT INTO `city` VALUES (296, 20, 'صلوات آباد');
INSERT INTO `city` VALUES (297, 20, 'حسن آباد');
INSERT INTO `city` VALUES (298, 21, 'كرمان');
INSERT INTO `city` VALUES (299, 21, 'راور');
INSERT INTO `city` VALUES (300, 21, 'بابك');
INSERT INTO `city` VALUES (301, 21, 'انار');
INSERT INTO `city` VALUES (302, 21, 'کوهبنان');
INSERT INTO `city` VALUES (303, 21, 'رفسنجان');
INSERT INTO `city` VALUES (304, 21, 'بافت');
INSERT INTO `city` VALUES (305, 21, 'سيرجان');
INSERT INTO `city` VALUES (306, 21, 'كهنوج');
INSERT INTO `city` VALUES (307, 21, 'زرند');
INSERT INTO `city` VALUES (308, 21, 'بم');
INSERT INTO `city` VALUES (309, 21, 'جيرفت');
INSERT INTO `city` VALUES (310, 21, 'بردسير');
INSERT INTO `city` VALUES (311, 22, 'كرمانشاه');
INSERT INTO `city` VALUES (312, 22, 'اسلام آباد غرب');
INSERT INTO `city` VALUES (313, 22, 'سر پل ذهاب');
INSERT INTO `city` VALUES (314, 22, 'كنگاور');
INSERT INTO `city` VALUES (315, 22, 'سنقر');
INSERT INTO `city` VALUES (316, 22, 'قصر شيرين');
INSERT INTO `city` VALUES (317, 22, 'گيلان غرب');
INSERT INTO `city` VALUES (318, 22, 'هرسين');
INSERT INTO `city` VALUES (319, 22, 'صحنه');
INSERT INTO `city` VALUES (320, 22, 'پاوه');
INSERT INTO `city` VALUES (321, 22, 'جوانرود');
INSERT INTO `city` VALUES (322, 22, 'شاهو');
INSERT INTO `city` VALUES (323, 23, 'ياسوج');
INSERT INTO `city` VALUES (324, 23, 'گچساران');
INSERT INTO `city` VALUES (325, 23, 'دنا');
INSERT INTO `city` VALUES (326, 23, 'دوگنبدان');
INSERT INTO `city` VALUES (327, 23, 'سي سخت');
INSERT INTO `city` VALUES (328, 23, 'دهدشت');
INSERT INTO `city` VALUES (329, 23, 'ليكك');
INSERT INTO `city` VALUES (330, 24, 'گرگان');
INSERT INTO `city` VALUES (331, 24, 'آق قلا');
INSERT INTO `city` VALUES (332, 24, 'گنبد كاووس');
INSERT INTO `city` VALUES (333, 24, 'علي آباد كتول');
INSERT INTO `city` VALUES (334, 24, 'مينو دشت');
INSERT INTO `city` VALUES (335, 24, 'تركمن');
INSERT INTO `city` VALUES (336, 24, 'كردكوي');
INSERT INTO `city` VALUES (337, 24, 'بندر گز');
INSERT INTO `city` VALUES (338, 24, 'كلاله');
INSERT INTO `city` VALUES (339, 24, 'آزاد شهر');
INSERT INTO `city` VALUES (340, 24, 'راميان');
INSERT INTO `city` VALUES (341, 25, 'رشت');
INSERT INTO `city` VALUES (342, 25, 'منجيل');
INSERT INTO `city` VALUES (343, 25, 'لنگرود');
INSERT INTO `city` VALUES (344, 25, 'رود سر');
INSERT INTO `city` VALUES (345, 25, 'تالش');
INSERT INTO `city` VALUES (346, 25, 'آستارا');
INSERT INTO `city` VALUES (347, 25, 'ماسوله');
INSERT INTO `city` VALUES (348, 25, 'آستانه اشرفيه');
INSERT INTO `city` VALUES (349, 25, 'رودبار');
INSERT INTO `city` VALUES (350, 25, 'فومن');
INSERT INTO `city` VALUES (351, 25, 'صومعه سرا');
INSERT INTO `city` VALUES (352, 25, 'بندرانزلي');
INSERT INTO `city` VALUES (353, 25, 'كلاچاي');
INSERT INTO `city` VALUES (354, 25, 'هشتپر');
INSERT INTO `city` VALUES (355, 25, 'رضوان شهر');
INSERT INTO `city` VALUES (356, 25, 'ماسال');
INSERT INTO `city` VALUES (357, 25, 'شفت');
INSERT INTO `city` VALUES (358, 25, 'سياهكل');
INSERT INTO `city` VALUES (359, 25, 'املش');
INSERT INTO `city` VALUES (360, 25, 'لاهیجان');
INSERT INTO `city` VALUES (361, 25, 'خشک بيجار');
INSERT INTO `city` VALUES (362, 25, 'خمام');
INSERT INTO `city` VALUES (363, 25, 'لشت نشا');
INSERT INTO `city` VALUES (364, 25, 'بندر کياشهر');
INSERT INTO `city` VALUES (365, 26, 'خرم آباد');
INSERT INTO `city` VALUES (366, 26, 'ماهشهر');
INSERT INTO `city` VALUES (367, 26, 'دزفول');
INSERT INTO `city` VALUES (368, 26, 'بروجرد');
INSERT INTO `city` VALUES (369, 26, 'دورود');
INSERT INTO `city` VALUES (370, 26, 'اليگودرز');
INSERT INTO `city` VALUES (371, 26, 'ازنا');
INSERT INTO `city` VALUES (372, 26, 'نور آباد');
INSERT INTO `city` VALUES (373, 26, 'كوهدشت');
INSERT INTO `city` VALUES (374, 26, 'الشتر');
INSERT INTO `city` VALUES (375, 26, 'پلدختر');
INSERT INTO `city` VALUES (376, 27, 'ساري');
INSERT INTO `city` VALUES (377, 27, 'آمل');
INSERT INTO `city` VALUES (378, 27, 'بابل');
INSERT INTO `city` VALUES (379, 27, 'بابلسر');
INSERT INTO `city` VALUES (380, 27, 'بهشهر');
INSERT INTO `city` VALUES (381, 27, 'تنكابن');
INSERT INTO `city` VALUES (382, 27, 'جويبار');
INSERT INTO `city` VALUES (383, 27, 'چالوس');
INSERT INTO `city` VALUES (384, 27, 'رامسر');
INSERT INTO `city` VALUES (385, 27, 'سواد كوه');
INSERT INTO `city` VALUES (386, 27, 'قائم شهر');
INSERT INTO `city` VALUES (387, 27, 'نكا');
INSERT INTO `city` VALUES (388, 27, 'نور');
INSERT INTO `city` VALUES (389, 27, 'بلده');
INSERT INTO `city` VALUES (390, 27, 'نوشهر');
INSERT INTO `city` VALUES (391, 27, 'پل سفيد');
INSERT INTO `city` VALUES (392, 27, 'محمود آباد');
INSERT INTO `city` VALUES (393, 27, 'فريدون كنار');
INSERT INTO `city` VALUES (394, 28, 'اراك');
INSERT INTO `city` VALUES (395, 28, 'آشتيان');
INSERT INTO `city` VALUES (396, 28, 'تفرش');
INSERT INTO `city` VALUES (397, 28, 'خمين');
INSERT INTO `city` VALUES (398, 28, 'دليجان');
INSERT INTO `city` VALUES (399, 28, 'ساوه');
INSERT INTO `city` VALUES (400, 28, 'سربند');
INSERT INTO `city` VALUES (401, 28, 'محلات');
INSERT INTO `city` VALUES (402, 28, 'شازند');
INSERT INTO `city` VALUES (403, 29, 'بندرعباس');
INSERT INTO `city` VALUES (404, 29, 'قشم');
INSERT INTO `city` VALUES (405, 29, 'كيش');
INSERT INTO `city` VALUES (406, 29, 'بندر لنگه');
INSERT INTO `city` VALUES (407, 29, 'بستك');
INSERT INTO `city` VALUES (408, 29, 'حاجي آباد');
INSERT INTO `city` VALUES (409, 29, 'دهبارز');
INSERT INTO `city` VALUES (410, 29, 'انگهران');
INSERT INTO `city` VALUES (411, 29, 'ميناب');
INSERT INTO `city` VALUES (412, 29, 'ابوموسي');
INSERT INTO `city` VALUES (413, 29, 'بندر جاسك');
INSERT INTO `city` VALUES (414, 29, 'تنب بزرگ');
INSERT INTO `city` VALUES (415, 29, 'بندر خمیر');
INSERT INTO `city` VALUES (416, 29, 'پارسیان');
INSERT INTO `city` VALUES (417, 29, 'قشم');
INSERT INTO `city` VALUES (418, 30, 'همدان');
INSERT INTO `city` VALUES (419, 30, 'ملاير');
INSERT INTO `city` VALUES (420, 30, 'تويسركان');
INSERT INTO `city` VALUES (421, 30, 'نهاوند');
INSERT INTO `city` VALUES (422, 30, 'كبودر اهنگ');
INSERT INTO `city` VALUES (423, 30, 'رزن');
INSERT INTO `city` VALUES (424, 30, 'اسدآباد');
INSERT INTO `city` VALUES (425, 30, 'بهار');
INSERT INTO `city` VALUES (426, 31, 'يزد');
INSERT INTO `city` VALUES (427, 31, 'تفت');
INSERT INTO `city` VALUES (428, 31, 'اردكان');
INSERT INTO `city` VALUES (429, 31, 'ابركوه');
INSERT INTO `city` VALUES (430, 31, 'ميبد');
INSERT INTO `city` VALUES (431, 31, 'طبس');
INSERT INTO `city` VALUES (432, 31, 'بافق');
INSERT INTO `city` VALUES (433, 31, 'مهريز');
INSERT INTO `city` VALUES (434, 31, 'اشكذر');
INSERT INTO `city` VALUES (435, 31, 'هرات');
INSERT INTO `city` VALUES (436, 31, 'خضرآباد');
INSERT INTO `city` VALUES (437, 31, 'شاهديه');
INSERT INTO `city` VALUES (438, 31, 'حمیدیه شهر');
INSERT INTO `city` VALUES (439, 31, 'سید میرزا');
INSERT INTO `city` VALUES (440, 31, 'زارچ');
