INSERT INTO `province` VALUES (1, 'آذربايجان شرقي');
INSERT INTO `province` VALUES (2, 'آذربايجان غربي');
INSERT INTO `province` VALUES (3, 'اردبيل');
INSERT INTO `province` VALUES (4, 'اصفهان');
INSERT INTO `province` VALUES (5, 'البرز');
INSERT INTO `province` VALUES (6, 'ايلام');
INSERT INTO `province` VALUES (7, 'بوشهر');
INSERT INTO `province` VALUES (8, 'تهران');
INSERT INTO `province` VALUES (9, 'چهارمحال بختياري');
INSERT INTO `province` VALUES (10, 'خراسان جنوبي');
INSERT INTO `province` VALUES (11, 'خراسان رضوي');
INSERT INTO `province` VALUES (12, 'خراسان شمالي');
INSERT INTO `province` VALUES (13, 'خوزستان');
INSERT INTO `province` VALUES (14, 'زنجان');
INSERT INTO `province` VALUES (15, 'سمنان');
INSERT INTO `province` VALUES (16, 'سيستان و بلوچستان');
INSERT INTO `province` VALUES (17, 'فارس');
INSERT INTO `province` VALUES (18, 'قزوين');
INSERT INTO `province` VALUES (19, 'قم');
INSERT INTO `province` VALUES (20, 'كردستان');
INSERT INTO `province` VALUES (21, 'كرمان');
INSERT INTO `province` VALUES (22, 'كرمانشاه');
INSERT INTO `province` VALUES (23, 'كهكيلويه و بويراحمد');
INSERT INTO `province` VALUES (24, 'گلستان');
INSERT INTO `province` VALUES (25, 'گيلان');
INSERT INTO `province` VALUES (26, 'لرستان');
INSERT INTO `province` VALUES (27, 'مازندران');
INSERT INTO `province` VALUES (28, 'مركزي');
INSERT INTO `province` VALUES (29, 'هرمزگان');
INSERT INTO `province` VALUES (30, 'همدان');
INSERT INTO `province` VALUES (31, 'يزد');
